# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/My Tresors/Diplomaterv/Github/Projects/Vivado/Counter/Counter.cache/wt} [current_project]
set_property parent.project_path {D:/My Tresors/Diplomaterv/Github/Projects/Vivado/Counter/Counter.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/My Tresors/Diplomaterv/Github/Projects/Vivado/Counter/Counter.srcs/sources_1/imports/Counter_Verilog_SrcFiles/Seg_7_Display.v}
  {D:/My Tresors/Diplomaterv/Github/Projects/Vivado/Counter/Counter.srcs/sources_1/new/bidirectional_counter.v}
  {D:/My Tresors/Diplomaterv/Github/Projects/Vivado/Counter/Counter.srcs/sources_1/imports/Counter_Verilog_SrcFiles/Basys3_Counter_Top.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/My Tresors/Diplomaterv/Github/Projects/Vivado/Counter/Counter.srcs/constrs_1/imports/Vivado_basys/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/My Tresors/Diplomaterv/Github/Projects/Vivado/Counter/Counter.srcs/constrs_1/imports/Vivado_basys/Basys3_Master.xdc}}]


synth_design -top Basys3_Counter_Top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Basys3_Counter_Top.dcp

catch { report_utilization -file Basys3_Counter_Top_utilization_synth.rpt -pb Basys3_Counter_Top_utilization_synth.pb }
